version: 0.2
phases:
  install:
    commands:
      - cd CICD
      - chmod +x aws-config.sh install-terraform.sh
      - pip install pre-commit terratest
  pre_build:
    commands:
      - ./aws-config.sh
      - ./install-terraform.sh
      - echo "Running pre-commit hooks"
      - pre-commit run --all-files
      - echo "Running Terraform format checks"
      - cd ../main && terraform fmt -check
  build:
    commands:
      - cd ..
      - cd main
      - terraform init
      - terraform validate
      - terraform apply -auto-approve 
      # - terraform destroy -auto-approve 

